<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocX" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\exambank.data\exambank.data.csproj" />
  </ItemGroup>

</Project>
